name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs once every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: theAnshul01
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
